### ISSUE TITLE
where are the files downloaded and how to change seed

### ISSUE THREAD

**Issue by FurkanGozukara** [ai-forever/Kandinsky-2#28]
I am recording a tutorial video

files are downloaded

but where?

also how to make seed random

![image](https://user-images.githubusercontent.com/19240467/230067948-badb3460-299c-4220-8192-5ff87c06619f.png)

**Comment by Blucknote** [comment]
@FurkanGozukara Did you find how to pass seed? I'm also interested in

**Comment by FurkanGozukara** [comment]
> @FurkanGozukara Did you find how to pass seed? I'm also interested in

well after i noticed it generates random seed every time i didn't spend more time to find the seed

I made a video as well

27.) Python Script - Jupyter Based - PC - Free
[**Midjourney Level NEW Open Source Kandinsky 2.1 Beats Stable Diffusion - Installation And Usage Guide**](https://youtu.be/dYt9xJ7dnpU)
[![image](https://user-images.githubusercontent.com/19240467/230183162-8a6f7e84-dcd9-45b5-a94c-b93a10778f42.png)
](https://youtu.be/dYt9xJ7dnpU)

**Comment by Blucknote** [comment]
> > @FurkanGozukara Did you find how to pass seed? I'm also interested in
> 
> well after i noticed it generates random seed every time i didn't spend more time to find the seed
> 
> I made a video as well
> 
> 27.) Python Script - Jupyter Based - PC - Free [**Midjourney Level NEW Open Source Kandinsky 2.1 Beats Stable Diffusion - Installation And Usage Guide**](https://youtu.be/dYt9xJ7dnpU) [![image](https://user-images.githubusercontent.com/19240467/230183162-8a6f7e84-dcd9-45b5-a94c-b93a10778f42.png) ](https://youtu.be/dYt9xJ7dnpU)

Thanks, but I already wrote script for txt2img: https://gist.github.com/Blucknote/31f792621f4e4cdf0a7d2505ddd6b0a2 without jupyter dependency

**Comment by FurkanGozukara** [comment]
@Blucknote thanks. i find using jupyter super convenient . runpod also uses same.
