### ISSUE TITLE
Fine tuning

### ISSUE THREAD

**Issue by nerodono** [ai-forever/Kandinsky-2#29]
Как эту модель fine tune'ить? Можно ли? Если нет - прошу добавить.

**Comment by FurkanGozukara** [comment]
Fine tuning would be amazing such as DreamBooth

**Comment by cene555** [comment]
Скрипты файнтюнинга анклипа и приора были добавлены

**Comment by nerodono** [comment]
> Скрипты файнтюнинга анклипа и приора были добавлены

Спасибо, было бы хорошо еще инструкцию для тюнинга модели в README.md поместить. Закрываю.

**Comment by kopyl** [comment]
@chiragverma it's a full fine-tune.

@cene555 right?
