### ISSUE TITLE
Runtime error using cpu instead of cuda 

### ISSUE THREAD

**Issue by LazyCat420** [ai-forever/Kandinsky-2#32]
Output exceeds the [size limit](command:workbench.action.openSettings?%5B%22notebook.output.textLineLimit%22%5D). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?aa4a39b2-6dbb-4cbb-ba21-5d9512d5e8eb)---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[3], line 1
----> 1 model = get_kandinsky2(
      2     'cuda', 
      3     task_type='text2img', 
      4     cache_dir='/tmp/kandinsky2', 
      5     model_version='2.1', 
      6     use_flash_attention=False
      7 )

File [f:\AI_Scripts\Kandinsky](file:///F:/AI_Scripts/Kandinsky) 2.1\2.1\Kandisky\lib\site-packages\kandinsky2\__init__.py:179, in get_kandinsky2(device, task_type, cache_dir, use_auth_token, model_version, use_flash_attention)
    172     model = get_kandinsky2_0(
    173         device,
    174         task_type=task_type,
    175         cache_dir=cache_dir,
    176         use_auth_token=use_auth_token,
    177     )
    178 elif model_version == "2.1":
--> 179     model = get_kandinsky2_1(
    180         device,
    181         task_type=task_type,
    182         cache_dir=cache_dir,
    183         use_auth_token=use_auth_token,
    184         use_flash_attention=use_flash_attention,
...
    170                        'to map your storages to the CPU.')
    171 device_count = torch.cuda.device_count()
    172 if device >= device_count:

RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

tried switching fp16 to false with the workaround from another thread wasn't able to get it to work.

**Comment by Blucknote** [comment]
#25 
You can try https://github.com/ai-forever/Kandinsky-2/issues/25#issuecomment-1496989866
Not tried, but will

**Comment by LazyCat420** [comment]
> 

I just tried that method and nothing changed...I decided to redo the entire env just in case I did something wrong on my end. If it ends up working I'll let you know.

**Comment by Blucknote** [comment]
> > 
> 
> I just tried that method and nothing changed...I decided to redo the entire env just in case I did something wrong on my end.

It was unnecessary to reinstall whole env, there was an options like `git stash` or `git reset --hard origin/master` which reset changes in code but does not affect venv.

> If it ends up working I'll let you know.

Thanks

**Comment by LazyCat420** [comment]
> > > 
> > 
> > 
> > I just tried that method and nothing changed...I decided to redo the entire env just in case I did something wrong on my end.
> 
> It was unnecessary to reinstall whole env, there was an options like `git stash` or `git reset --hard origin/master` which reset changes in code but does not affect venv.
> 
> > If it ends up working I'll let you know.
> 
> Thanks

ran the bat file from this github and got it to work. I think it was just missing some dependencies. 

https://github.com/ai-forever/Kandinsky-2/issues/33#issue-1656316980
