### ISSUE TITLE
Style transfer instructions?

### ISSUE THREAD

**Issue by dokluch** [ai-forever/Kandinsky-2#46]
Hi! Do you have instructions to recreate style transfer as mentioned in the model description on Habr?

**Comment by Blucknote** [comment]
You can use https://github.com/ai-forever/Kandinsky-2/blob/main/notebooks/kandinsky_2_1_mixing.ipynb as refference

[Here](https://github.com/Blucknote/Kandinsky-advanced-notebooks) another notebook with UI elements if you plan to use notebooks at all
