### ISSUE TITLE
UnboundLocalError: local variable 'config_file_url' referenced before assignment

### ISSUE THREAD

**Issue by MohamedAliRashad** [ai-forever/Kandinsky-2#51]
The error in the title show up when i try to load multiple models from `get_kandinsky2` for different tasks

```python
text2img_model = get_kandinsky2("cuda", task_type="text2img", model_version="2.1", use_flash_attention=True)
img2img_model = get_kandinsky2("cuda", task_type="img2img", model_version="2.1", use_flash_attention=True)
```

**Comment by Blucknote** [comment]
There is no such task type (yet?) in Kandinsky2.1 
https://github.com/ai-forever/Kandinsky-2/blob/c9ec0dda37bdf98bbfa5d548d2cebcdf7a366ac2/kandinsky2/__init__.py#L99-L104
